// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: books.sql

package db

import (
	"context"
)

const getBooks = `-- name: GetBooks :many
SELECT id, name, created_at FROM "books" LIMIT $1 OFFSET $2
`

type GetBooksParams struct {
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) GetBooks(ctx context.Context, arg GetBooksParams) ([]*Book, error) {
	rows, err := q.db.Query(ctx, getBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
