// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID        int64              `db:"id"`
	Name      string             `db:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

type Order struct {
	ID        int64              `db:"id"`
	UserID    int64              `db:"user_id"`
	BookID    pgtype.Int8        `db:"book_id"`
	Amount    pgtype.Int8        `db:"amount"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	Details   []byte             `db:"details"`
}

type User struct {
	ID        int64              `db:"id"`
	Email     string             `db:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}
