// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, userID int64) (*CreateOrderRow, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (*OrderItem, error)
	CreateUser(ctx context.Context, email string) (*User, error)
	FindBook(ctx context.Context, id int64) (*Book, error)
	FindUser(ctx context.Context, email string) (*User, error)
	FindUserByToken(ctx context.Context, token pgtype.Text) (*User, error)
	GetBooks(ctx context.Context, arg GetBooksParams) ([]*Book, error)
	GetMyOrders(ctx context.Context, arg GetMyOrdersParams) ([]*GetMyOrdersRow, error)
}

var _ Querier = (*Queries)(nil)
