// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*CreateOrderRow, error)
	CreateUser(ctx context.Context, email string) (*User, error)
	FindBook(ctx context.Context, id int64) (*Book, error)
	FindOrder(ctx context.Context, id int64) (*FindOrderRow, error)
	FindUser(ctx context.Context, email string) (*User, error)
	GetBooks(ctx context.Context, arg GetBooksParams) ([]*Book, error)
	GetMyOrders(ctx context.Context, arg GetMyOrdersParams) ([]*GetMyOrdersRow, error)
}

var _ Querier = (*Queries)(nil)
