version: '3.7'
services:
  postgresd:
    image: postgres:13.7
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    networks:
      - intranet
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

networks:
  intranet:
